### ISSUE TITLE
Nody Greeter working but cannot connect to socket

### ISSUE THREAD

**Issue by yetser77** [JezerM/nody-greeter#16]
I managed to get nody-greeter working, but it's saying it cannot connect to socket. Also, my LightDM has error start request too quickly. How do I fix this?

**Comment by JezerM** [comment]
Could you provide the `nody-greeter` log?

**Comment by yetser77** [comment]
nody-greeter
2022-02-10 08:15:52 [ DEBUG ] browser.js 117: Initializing Browser Window
2022-02-10 08:15:52 [ DEBUG ] browser.js 169: Browser Window created
2022-02-10 08:15:52 [ DEBUG ] screensaver.js 39: Screensaver set
2022-02-10 08:15:52 [ DEBUG ] browser.js 114: Theme loaded
2022-02-10 08:15:52 [ DEBUG ] globals.js 15: Javascript logger is ready
2022-02-10 08:15:52 [ DEBUG ] globals.js 12: Window is ready
2022-02-10 08:15:52 [ ERROR ] bridge.js 48: Error: Unable to determine socket to daemon
2022-02-10 08:15:52 [ DEBUG ] bridge.js 65: LightDM API connected
2022-02-10 08:16:02 [ DEBUG ] browser.js 190: Nody Greeter started win: 3
^C2022-02-10 08:16:05 [ DEBUG ] screensaver.js 54: Screensaver reset
2022-02-10 08:16:05 [ DEBUG ] acpi.js 61: Restarting acpi_listen

**Comment by JezerM** [comment]
Does this occurs when **logged in** (inside a Desktop Environment/Window Manager) or inside the **LightDM environment** (when trying to log in)?

**Comment by Adog64** [comment]
> I can't even run `nody-greeter` in Fedora, the window is never shown... Sincerely, I don't know why.

I can get almost everything working in Fedora Cinnamon. Everything runs and displays properly in debug and normal mode, but light-dm keeps loading the default login configuration.

**Comment by admin-ribbon** [comment]
Hello
I dunno if this a correct place to report this
But I got the same problem as the OP
Except while I can load the Nody Greeter itself, the log in doesn't work at all

**Comment by admin-ribbon** [comment]
[4682:1118/144726.476998:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags
2022-11-18 14:47:26 [ DEBUG ] browser.js 125: Initializing Browser Window
2022-11-18 14:47:26 [ DEBUG ] browser.js 177: Browser Window created
2022-11-18 14:47:26 [ DEBUG ] screensaver.js 42: Screensaver set
2022-11-18 14:47:26 [ DEBUG ] browser.js 122: Theme loaded
2022-11-18 14:47:26 [ DEBUG ] globals.js 16: Javascript logger is ready
2022-11-18 14:47:26 [ DEBUG ] globals.js 13: Window is ready
2022-11-18 14:47:26 [ ERROR ] bridge.js 53: Error: Unable to determine socket to daemon
    at new Greeter (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:49:28)
    at Function.getInstance (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:99:52)
    at /opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:718:37
[4682:1118/144726.936463:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
2022-11-18 14:47:26 [ DEBUG ] bridge.js 70: LightDM API connected
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[4719:1118/144726.976044:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[4755:1118/144727.040000:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-11-18 14:47:30 [ DEBUG ] browser.js 198: Nody Greeter started win: 70
[4682:1118/144730.593309:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_cancel_authentication: assertion 'priv->connected' failed
[4682:1118/144730.593599:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_authenticate: assertion 'priv->connected' failed
[4682:1118/144735.058851:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144736.512987:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144737.982150:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144738.127537:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144738.325582:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144738.499125:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144744.931389:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144747.045895:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144747.258347:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
[4682:1118/144747.457399:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
2022-11-18 14:47:52 [ DEBUG ] screensaver.js 58: Screensaver reset

**Comment by admin-ribbon** [comment]
Bug demo
https://imgur.com/a/ihVPXRV

**Comment by JezerM** [comment]
@admin-ribbon Make sure you have set `X-LightDM-Allow-Greeter=true` inside your desktop session in `/usr/share/xsessions/`. This allows to access to the LightDM API in a normal session and hence it should solve your issue.

**Comment by trongtri35** [comment]
> @admin-ribbon Make sure you have set `X-LightDM-Allow-Greeter=true` inside your desktop session in `/usr/share/xsessions/`. This allows to access to the LightDM API in a normal session and hence it should solve your issue.

i have the same error, and add `X-LightDM-Allow-Greeter=true` in `lightdm-xsession.desktop` but nothing happen, still errors!
i use debian 11, bspwm lightdm

**Comment by 3ab3z2** [comment]
I have nearly the same issue here, in debian 12 with xfce.
```
--->nody-greeter --debug
[3910:0223/113043.666392:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags 
2024-02-23 11:30:43 [ ERROR ] acpi.js 36: ACPI: acpi_listen does not exists
2024-02-23 11:30:43 [ DEBUG ] browser.js 125: Initializing Browser Window
2024-02-23 11:30:43 [ DEBUG ] browser.js 177: Browser Window created
2024-02-23 11:30:43 [ DEBUG ] screensaver.js 42: Screensaver set
2024-02-23 11:30:43 [ DEBUG ] browser.js 122: Theme loaded
2024-02-23 11:30:43 [ DEBUG ] globals.js 16: Javascript logger is ready
2024-02-23 11:30:43 [ DEBUG ] globals.js 13: Window is ready
2024-02-23 11:30:44 [ ERROR ] bridge.js 53: Error: Unable to determine socket to daemon
    at new Greeter (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:49:28)
    at Function.getInstance (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:99:52)
    at /opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:718:37
[3910:0223/113044.009476:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
2024-02-23 11:30:44 [ DEBUG ] bridge.js 70: LightDM API connected
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[3942:0223/113044.012296:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
2024-02-23 11:30:48 [ DEBUG ] browser.js 198: Nody Greeter started win: 2785062953156674
[3910:0223/113048.358068:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_authenticate: assertion 'priv->connected' failed
2024-02-23 11:30:50 [ DEBUG ] screensaver.js 58: Screensaver reset
```
![image](https://github.com/JezerM/nody-greeter/assets/126415531/b8b6765d-b60e-413d-bb86-3bffbaad662d)
