### ISSUE TITLE
Issue with build.js when running sudo node make install

### ISSUE THREAD

**Issue by stuckinthe** [JezerM/nody-greeter#32]
## Environment
- OS: Ubuntu Mate 22.04
- nody-greeter version: output of `nody-greeter --version`

## Bug description
Syntax error during sudo node make install

## Steps to reproduce
followed the instructions without issue and then received an error in the sudo node make install

## Expected behavior
Install

## Screenshots
`(node:2683) UnhandledPromiseRejectionWarning: /home/joe/nody-greeter/build.js:176
    const minor = electronMatch.groups.minor ?? "0";
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at do_install (/home/joe/nody-greeter/make.js:62:21)
    at Object.<anonymous> (/home/joe/nody-greeter/make.js:85:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
(node:2683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by JezerM** [comment]
This should be fixed if you're using Node.js v12.
