### ISSUE TITLE
theme can not recoginige correct monitor resolution

### ISSUE THREAD

**Issue by racagogi** [JezerM/nody-greeter#33]
## Environment
- OS: Arch linux
- nody-greeter version: 1.5.1
- theme: [lightdm-webkit-theme-litarvan](https://github.com/Litarvan/lightdm-webkit-theme-litarvan) master branch
- xrandr properties
```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
HDMI-0 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 620mm x 350mm
	CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
		0 1 
	CscMatrix: 65536 0 0 0 0 65536 0 0 0 0 65536 0 
	BorderDimensions: 4 
		supported: 4
	Border: 0 0 0 0 
		range: (0, 65535)
	SignalFormat: TMDS 
		supported: TMDS
	ConnectorType: HDMI 
	ConnectorNumber: 2 
	_ConnectorLocation: 2 
	non-desktop: 0 
		supported: 0, 1
   3840x2160     59.98*+  59.94    50.00    30.00    29.97    25.00    23.98  
   1920x1080     60.00    60.00    59.94    50.00    29.97    25.00    23.98  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00    29.97    25.00    23.98  
   1024x768      60.00  
   800x600       60.32  
   720x480       59.94  
   640x480       59.94    59.93  
```
- nody-greeter log
```
[3629:0926/165827.350019:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags
2022-09-26 16:58:27 [ ERROR ] acpi.js 36: ACPI: acpi_listen does not exists
2022-09-26 16:58:27 [ DEBUG ] browser.js 125: Initializing Browser Window
2022-09-26 16:58:27 [ DEBUG ] browser.js 177: Browser Window created
2022-09-26 16:58:27 [ DEBUG ] screensaver.js 42: Screensaver set
2022-09-26 16:58:27 [ DEBUG ] browser.js 122: Theme loaded
2022-09-26 16:58:27 [ DEBUG ] globals.js 16: Javascript logger is ready
2022-09-26 16:58:27 [ DEBUG ] globals.js 13: Window is ready
2022-09-26 16:58:27 [ ERROR ] bridge.js 53: Error: Unable to determine socket to daemon
    at new Greeter (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:49:28)
    at Function.getInstance (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:99:52)
    at /opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:718:37
[3629:0926/165827.822005:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
2022-09-26 16:58:27 [ DEBUG ] bridge.js 70: LightDM API connected
[3629:0926/165829.517555:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_cancel_authentication: assertion 'priv->connected' failed
[3629:0926/165829.517871:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_authenticate: assertion 'priv->connected' failed
2022-09-26 16:58:29 [ DEBUG ] browser.js 198: Nody Greeter started win: 0
```
## Bug description
Litervan theme can not recognize correct resolution at 3840x2160. But correctly work at 1280x1024.  

nody-greeter --debug shows that a threshold size makes this anomalous. The screenshot below shows this.

I have used this theme before based on lightdm-webkit2-greeter in the same environment, at that time it worked correctly.
I check base gruvbox theme, it work correctly

## Steps to reproduce

Build the latest nody-greeter and litervan themes and run them at 3840x2160.

## Screenshots
![2022-09-26-16-59-07](https://user-images.githubusercontent.com/97871898/192225365-7d8d0309-ab12-4fd6-a64b-07def05b9772.png)
this works normally
![2022-09-26-16-59-36](https://user-images.githubusercontent.com/97871898/192225387-88d656cb-fbdd-4089-831a-2a71155222a7.png)
this works anomaly

**Comment by racagogi** [comment]
yes, only this greeter theme cause this problem.
here is my latop graphic configuration
```
integrated graphics -> pci-5 -> 1280x1024 
Discrete Graphics -> pci-1 -> 3840x2160
``` 
I use only discrete graphics, so only 3840x2160 monitor activate. But this greeter seem to multi-monitor setting, I think multi monitor support may collision between greeters.

anyway, now I use base gruvbox theme without any problem.

**Comment by JezerM** [comment]
Also, does this happen in the Login environment too (when you're going to start a session)? Or is this a desktop only issue (when you're already logged in)?

**Comment by racagogi** [comment]
Also happen in the login environment. actually greeter size is only critial, in 1280x1024 size integrated graphics monitor, it correctly work.
