### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by jackzzs** [JezerM/nody-greeter#4]
Install all the dependencies and install the released deb, run nody-greeter, error occurs.

**Comment by JezerM** [comment]
Could you provide more info? Like the full terminal output.

**Comment by mshernandez5** [comment]
I just tried installing nody-greeter on a virtual machine to check it out and have the same issue when running `nody-greeter --debug` (I do have the X-LightDM-Allow-Greeter setting enabled also).

The full output is:
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at new BrightnessController (/opt/nody-greeter/resources/app.asar/js/utils/brightness.js:56:38)
    at Object.<anonymous> (/opt/nody-greeter/resources/app.asar/js/utils/brightness.js:119:20)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
```

I would guess that the problem lies in https://github.com/JezerM/nody-greeter/blob/master/ts/utils/brightness.ts#L51 due to `path` being undefined; why this is the case though I am not sure.

I installed using the v1.2.0 .deb package on the releases page using Linux Mint 20.

**Comment by mshernandez5** [comment]
Built it myself and no more issue, only happens when using the pre-built package for some reason.

**Comment by JezerM** [comment]
Pre-build deb packages are built in Ubuntu 20.04 and newer. It's possible that they don't work on other debian based distros, but I'm not sure at all. However, this issue is related to the brightness util itself, which is expected to be fixed if you build it by yourself :D
