### ISSUE TITLE
Unexpected reserved word Issue when running npm run build

### ISSUE THREAD

**Issue by chaogamer** [JezerM/nody-greeter#53]
![image](https://github.com/user-attachments/assets/92821548-cd08-4e6b-a6db-e19568d41905)

the rebuild ran fine perfectly and the installation found 0 vulnerabilities. what is the issue?

**Comment by JezerM** [comment]
Which node version are you using?

**Comment by chaogamer** [comment]
> Which node version are you using?

v12.22.9

**Comment by JezerM** [comment]
Yeah, that's a pretty old version. The recommended version is v18.

**Comment by chaogamer** [comment]
> Yeah, that's a pretty old version. The recommended version is v18. Try it again with node 18 :D

managed to do so, it is fixed, though now i have an issue with LightDM itself

i get this error during the debugging session
![image](https://github.com/user-attachments/assets/1f3da908-fe89-47d2-8d3d-1b57e1f9745d)
anyway to fix this so i can be able to login?

**Comment by JezerM** [comment]
Ah, that's expected when running in debug mode. As there's no active lightdm environment, it will show an error. You could try to run it with `lightdm --test-mode`, which runs a lightdm window with the greeter inside (you must change the greeter that lightdm uses to set nody-greeter).

**Comment by chaogamer** [comment]
> Ah, that's expected when running in debug mode. As there's no active lightdm environment, it will show an error. You could try to run it with `lightdm --test-mode`, which runs a lightdm window with the greeter inside (you must change the greeter that lightdm uses to set nody-greeter).

![image](https://github.com/user-attachments/assets/97704c6d-9969-42b4-86c3-beb81a1867a0)


also when trying to login non debug, it says fails to load session, return error code 1. and asks me to reload theme or switch to default

**Comment by chaogamer** [comment]
> > Ah, that's expected when running in debug mode. As there's no active lightdm environment, it will show an error. You could try to run it with `lightdm --test-mode`, which runs a lightdm window with the greeter inside (you must change the greeter that lightdm uses to set nody-greeter).
> 
> ![image](https://private-user-images.githubusercontent.com/76564608/355218283-97704c6d-9969-42b4-86c3-beb81a1867a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODYzMzksIm5iZiI6MTcyMjg4NjAzOSwicGF0aCI6Ii83NjU2NDYwOC8zNTUyMTgyODMtOTc3MDRjNmQtOTk2OS00MmI0LTg2YzMtYmViODFhMTg2N2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE5MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OTEyY2EyMzViNWQxYWE1Y2M1ODk0YmZjNDUxOGJmY2U2ZTI0YzcwMmRhZTdjNzRlNTA0YTNiMWQ2ZmQ1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jLFLyedDw18bvFOVqdtJeogD76JEPdak14gWZqRNrU)
> 
> also when trying to login non debug, it says fails to load session, return error code 1. and asks me to reload theme or switch to default

![image](https://github.com/user-attachments/assets/5f13e0f4-2a87-463b-ad35-3a87aad4da87)
plus this

**Comment by chaogamer** [comment]
> > > Ah, that's expected when running in debug mode. As there's no active lightdm environment, it will show an error. You could try to run it with `lightdm --test-mode`, which runs a lightdm window with the greeter inside (you must change the greeter that lightdm uses to set nody-greeter).
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/76564608/355218283-97704c6d-9969-42b4-86c3-beb81a1867a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODYzMzksIm5iZiI6MTcyMjg4NjAzOSwicGF0aCI6Ii83NjU2NDYwOC8zNTUyMTgyODMtOTc3MDRjNmQtOTk2OS00MmI0LTg2YzMtYmViODFhMTg2N2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE5MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OTEyY2EyMzViNWQxYWE1Y2M1ODk0YmZjNDUxOGJmY2U2ZTI0YzcwMmRhZTdjNzRlNTA0YTNiMWQ2ZmQ1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jLFLyedDw18bvFOVqdtJeogD76JEPdak14gWZqRNrU)
> > also when trying to login non debug, it says fails to load session, return error code 1. and asks me to reload theme or switch to default
> 
> ![image](https://private-user-images.githubusercontent.com/76564608/355218630-5f13e0f4-2a87-463b-ad35-3a87aad4da87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODY0MTEsIm5iZiI6MTcyMjg4NjExMSwicGF0aCI6Ii83NjU2NDYwOC8zNTUyMTg2MzAtNWYxM2UwZjQtMmE4Ny00NjNiLWFkMzUtM2E4N2FhZDRkYTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE5MjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjU3OTY0Njk4OTA4MWE4ZjI2NDZkOTI4NzAyMjI2Yzk4ZmI2NDdmODk1NGY1NDBkNTI5ZWE2NTE2ZmU2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7vw149CrPQ5yJ-u-xAzexg4yPtSz1UAwC9S_vvce6Cg) plus this

the logs:
![image](https://github.com/user-attachments/assets/81766274-c6c2-41de-b510-f77b707b1a1c)
![image](https://github.com/user-attachments/assets/c01a50b5-2c9d-4980-8126-1610aeaefb75)

**Comment by JezerM** [comment]
1. Which Linux distro are you using?
2. Could you provide the logs at `/var/log/lightdm/lightdm.log` and `/var/log/lightdm/seat0-greeter.log`?

**Comment by chaogamer** [comment]
> 1. Which Linux distro are you using?
> 
>     2. Could you provide the logs at `/var/log/lightdm/lightdm.log` and `/var/log/lightdm/seat0-greeter.log`?
> 
>     3. Do you have any other Login Manager such as GDM or SDDM? Is this active maybe?


1. Zorin OS
2.`[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=1039
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-log-backup.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-guest-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /var/lib/flatpak/exports/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/xdg/lightdm/lightdm.conf.d/90-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG:   [Seat:*] contains unknown option logind-check-graphical
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Seat seat0: Creating display server of type x
[+0.04s] DEBUG: Seat seat0: Plymouth is running on VT 1, but this is less than the configured minimum of 7 so not replacing it
[+0.04s] DEBUG: Quitting Plymouth
[+0.11s] DEBUG: Using VT 7
[+0.11s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.11s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.11s] DEBUG: XServer 0: Writing X server authority to /var/run/lightdm/root/:0
[+0.11s] DEBUG: XServer 0: Launching X Server
[+0.11s] DEBUG: Launching process 1094: /usr/bin/X -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.11s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.11s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.11s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.11s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.11s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+2.74s] DEBUG: Got signal 10 from process 1094
[+2.74s] DEBUG: XServer 0: Got signal from X server :0
[+2.74s] DEBUG: XServer 0: Connecting to XServer :0
[+2.89s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+2.89s] DEBUG: Session pid=1172: Started with service 'lightdm-greeter', username 'lightdm'
[+2.94s] DEBUG: Session pid=1172: Authentication complete with return value 0: Success
[+2.94s] DEBUG: Seat seat0: Session authenticated, running command
[+2.94s] DEBUG: Session pid=1172: Running command /etc/lightdm/Xgreeter /usr/bin/nody-greeter
[+2.94s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
[+2.94s] DEBUG: Session pid=1172: Logging to /var/log/lightdm/seat0-greeter.log
[+3.28s] DEBUG: Activating VT 7
[+3.28s] DEBUG: Activating login1 session c1
[+3.28s] DEBUG: Seat seat0 changes active session to c1
[+3.28s] DEBUG: Session c1 is already active
[+4.81s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
[+4.82s] DEBUG: Greeter requests data directory for user winme11
[+4.82s] DEBUG: Creating shared data directory /var/lib/lightdm-data/winme11
[+7.41s] DEBUG: Greeter start authentication for winme11
[+7.41s] DEBUG: Session pid=1421: Started with service 'lightdm', username 'winme11'
[+7.42s] DEBUG: Session pid=1421: Got 1 message(s) from PAM
[+7.42s] DEBUG: Prompt greeter with 1 message(s)
[+11.84s] DEBUG: Continue authentication
[+11.88s] DEBUG: Session pid=1421: Authentication complete with return value 0: Success
[+11.88s] DEBUG: Authenticate result for user winme11: Success
[+11.88s] DEBUG: User winme11 authorized
[+12.89s] DEBUG: Greeter requests session ubuntu
[+12.89s] DEBUG: Seat seat0: Failed to find session configuration ubuntu
[+12.89s] DEBUG: Seat seat0: Can't find session 'ubuntu'
[+175.61s] DEBUG: Seat seat0 changes active session to 
[+188.75s] DEBUG: Seat seat0 changes active session to 2
[+206.75s] DEBUG: Got signal 15 from process 1
[+206.75s] DEBUG: Caught Terminated signal, shutting down
[+206.75s] DEBUG: Stopping display manager
[+206.75s] DEBUG: Seat seat0: Stopping
[+206.75s] DEBUG: Seat seat0: Stopping display server
[+206.75s] DEBUG: Sending signal 15 to process 1094
[+206.75s] DEBUG: Seat seat0: Stopping session
[+206.75s] DEBUG: Terminating login1 session c1
[+206.76s] DEBUG: Session pid=1172: Sending SIGTERM
[+206.76s] DEBUG: Seat seat0: Stopping session
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] WARNING: Session pid=1421: Error writing to session: Broken pipe
[+206.76s] DEBUG: Session pid=1421: Terminated with signal 15
[+206.76s] DEBUG: Seat seat0: Session stopped
[+206.78s] DEBUG: Process 1094 exited with return value 0
[+206.78s] DEBUG: XServer 0: X server stopped
[+206.78s] DEBUG: Releasing VT 7
[+206.78s] DEBUG: XServer 0: Removing X server authority /var/run/lightdm/root/:0
[+206.78s] DEBUG: Seat seat0: Display server stopped
[+206.83s] DEBUG: Greeter closed communication channel
[+206.83s] DEBUG: Session pid=1172: Exited with return value 1
[+206.83s] DEBUG: Seat seat0: Session stopped
[+206.83s] DEBUG: Seat seat0: Stopped
[+206.83s] DEBUG: Display manager stopped
[+206.83s] DEBUG: Stopping daemon
[+206.83s] DEBUG: Exiting with return value 0
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=1629
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-log-backup.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-guest-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /var/lib/flatpak/exports/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/xdg/lightdm/lightdm.conf.d/90-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG:   [Seat:*] contains unknown option logind-check-graphical
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Seat seat0: Creating display server of type x
[+0.02s] DEBUG: Using VT 7
[+0.02s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.02s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.02s] DEBUG: XServer 0: Writing X server authority to /var/run/lightdm/root/:0
[+0.02s] DEBUG: XServer 0: Launching X Server
[+0.02s] DEBUG: Launching process 1635: /usr/bin/X -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.02s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.02s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.02s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.03s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.08s] DEBUG: Seat seat0 changes active session to 
[+2.10s] DEBUG: Got signal 10 from process 1635
[+2.10s] DEBUG: XServer 0: Got signal from X server :0
[+2.10s] DEBUG: XServer 0: Connecting to XServer :0
[+2.28s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+2.28s] DEBUG: Session pid=1663: Started with service 'lightdm-greeter', username 'lightdm'
[+2.32s] DEBUG: Session pid=1663: Authentication complete with return value 0: Success
[+2.32s] DEBUG: Seat seat0: Session authenticated, running command
[+2.32s] DEBUG: Session pid=1663: Running command /etc/lightdm/Xgreeter /usr/bin/nody-greeter
[+2.32s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
[+2.32s] DEBUG: Session pid=1663: Logging to /var/log/lightdm/seat0-greeter.log
[+2.69s] DEBUG: Activating VT 7
[+2.69s] DEBUG: Activating login1 session c2
[+2.69s] DEBUG: Seat seat0 changes active session to c2
[+2.69s] DEBUG: Session c2 is already active
[+3.52s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
[+3.53s] DEBUG: Greeter requests data directory for user winme11
[+3.53s] DEBUG: Creating shared data directory /var/lib/lightdm-data/winme11
[+5.55s] DEBUG: Greeter start authentication for winme11
[+5.55s] DEBUG: Session pid=1831: Started with service 'lightdm', username 'winme11'
[+5.57s] DEBUG: Session pid=1831: Got 1 message(s) from PAM
[+5.57s] DEBUG: Prompt greeter with 1 message(s)
[+7.90s] DEBUG: Continue authentication
[+7.95s] DEBUG: Session pid=1831: Authentication complete with return value 0: Success
[+7.95s] DEBUG: Authenticate result for user winme11: Success
[+7.95s] DEBUG: User winme11 authorized
[+8.96s] DEBUG: Greeter requests session ubuntu
[+8.96s] DEBUG: Seat seat0: Failed to find session configuration ubuntu
[+8.96s] DEBUG: Seat seat0: Can't find session 'ubuntu'
[+13.26s] DEBUG: Seat seat0 changes active session to 2
[+94.69s] DEBUG: Got signal 15 from process 1
[+94.69s] DEBUG: Caught Terminated signal, shutting down
[+94.69s] DEBUG: Stopping display manager
[+94.69s] DEBUG: Seat seat0: Stopping
[+94.69s] DEBUG: Seat seat0: Stopping display server
[+94.69s] DEBUG: Sending signal 15 to process 1635
[+94.69s] DEBUG: Seat seat0: Stopping session
[+94.69s] DEBUG: Terminating login1 session c2
[+94.82s] DEBUG: Session pid=1663: Sending SIGTERM
[+94.82s] DEBUG: Seat seat0: Stopping session
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] WARNING: Session pid=1831: Error writing to session: Broken pipe
[+94.82s] DEBUG: Process 1635 exited with return value 0
[+94.82s] DEBUG: XServer 0: X server stopped
[+94.82s] DEBUG: Releasing VT 7
[+94.82s] DEBUG: XServer 0: Removing X server authority /var/run/lightdm/root/:0
[+94.82s] DEBUG: Seat seat0: Display server stopped
[+94.82s] DEBUG: Session pid=1831: Terminated with signal 15
[+94.82s] DEBUG: Seat seat0: Session stopped
[+94.82s] DEBUG: Seat seat0 changes active session to 
[+94.82s] DEBUG: Greeter closed communication channel
[+94.82s] DEBUG: Session pid=1663: Exited with return value 0
[+94.82s] DEBUG: Seat seat0: Session stopped
[+94.82s] DEBUG: Seat seat0: Stopped
[+94.82s] DEBUG: Display manager stopped
[+94.82s] DEBUG: Stopping daemon
[+94.82s] DEBUG: Exiting with return value 0
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=5043
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-log-backup.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-guest-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/xdg/lightdm/lightdm.conf.d/90-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG:   [Seat:*] contains unknown option logind-check-graphical
[+0.00s] DEBUG: Using Xephyr for X servers
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.02s] DEBUG: Monitoring logind for seats
[+0.02s] DEBUG: New seat added from logind: seat0
[+0.02s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.02s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.02s] DEBUG: Seat seat0: Starting
[+0.02s] DEBUG: Seat seat0: Creating greeter session
[+0.02s] DEBUG: Seat seat0: Creating display server of type x
[+0.02s] DEBUG: Using VT 7
[+0.02s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.02s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.02s] DEBUG: XServer 0: Writing X server authority to /var/run/lightdm/root/:0
[+0.02s] DEBUG: XServer 0: Launching X Server
[+0.02s] DEBUG: Launching process 5049: /usr/bin/Xephyr :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.02s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.02s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.02s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.03s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1000 added` 

here's the lightdm.log

`2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Initializing Browser Window
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Browser Window created
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Screensaver set
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Theme loaded
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Javascript logger is ready
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Window is ready
2024-08-05 14:10:10 [ DEBUG ] index.cjs 6: LightDM API connected
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Nody Greeter started win: 66
2024-08-05 14:10:10 [ DEBUG ] index.cjs 4: Nody Greeter started win: 65
[1195:0805/141011.072354:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2024-08-05 14:10:18 [ ERROR ] index.cjs 6: Error: Session returned error code 1
    at ut.start_session (/opt/nody-greeter/resources/app.asar/out/main/index.cjs:6:3504)
    at H (/opt/nody-greeter/resources/app.asar/out/main/index.cjs:7:1871)
    at IpcMainImpl.<anonymous> (/opt/nody-greeter/resources/app.asar/out/main/index.cjs:7:2330)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:80427)
    at WebContents.emit (node:events:514:28)
2024-08-05 14:14:09 [ DEBUG ] index.cjs 4: Initializing Browser Window
2024-08-05 14:14:09 [ DEBUG ] index.cjs 4: Browser Window created
2024-08-05 14:14:09 [ DEBUG ] index.cjs 4: Screensaver set
2024-08-05 14:14:09 [ DEBUG ] index.cjs 4: Theme loaded
2024-08-05 14:14:10 [ DEBUG ] index.cjs 4: Javascript logger is ready
2024-08-05 14:14:10 [ DEBUG ] index.cjs 4: Window is ready
2024-08-05 14:14:10 [ DEBUG ] index.cjs 6: LightDM API connected
2024-08-05 14:14:10 [ DEBUG ] index.cjs 4: Nody Greeter started win: 66
2024-08-05 14:14:10 [ DEBUG ] index.cjs 4: Nody Greeter started win: 65
[1683:0805/141410.930735:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2024-08-05 14:14:15 [ ERROR ] index.cjs 6: Error: Session returned error code 1
    at ut.start_session (/opt/nody-greeter/resources/app.asar/out/main/index.cjs:6:3504)
    at H (/opt/nody-greeter/resources/app.asar/out/main/index.cjs:7:1871)
    at IpcMainImpl.<anonymous> (/opt/nody-greeter/resources/app.asar/out/main/index.cjs:7:2330)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:80427)
    at WebContents.emit (node:events:514:28)`

and here's the seat0-greeter.log

3.i have both installed and they do work. but i should have disabled both of them before starting lightdm

**Comment by JezerM** [comment]
Hi, sorry for the late response. This seems a LightDM error, perhaps? The greeter seems to have issues to retrieve data from LightDM. Have you tried another greeter like `lightdm-gtk-greeter`? Does `lightdm-gtk-greeter` work?
