### ISSUE TITLE
Error in Void Linux while installing

### ISSUE THREAD

**Issue by austinrojers** [JezerM/nody-greeter#8]
## Environment
- OS: Void Linux
- nody-greeter version: not able to install

```
Inspiron_15_3567% node --version
v16.9.1
```

## Bug description
```
Inspiron_15_3567% git clone https://github.com/JezerM/nody-greeter.git
cd nody-greeter
npm install
npm run rebuild
npx tsc --build
node make build
sudo node make install
Cloning into 'nody-greeter'...
remote: Enumerating objects: 540, done.
remote: Counting objects: 100% (540/540), done.
remote: Compressing objects: 100% (353/353), done.
remote: Total 540 (delta 248), reused 460 (delta 170), pack-reused 0
Receiving objects: 100% (540/540), 6.07 MiB | 1012.00 KiB/s, done.
Resolving deltas: 100% (248/248), done.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 463 packages, and audited 464 packages in 10s

40 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> nody-greeter@1.2.1 rebuild
> electron-rebuild -w node-gtk

⠸ Building module: node-gtk, Completed: 0gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
⠼ Building module: node-gtk, Completed: 0(node:3287) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gtk/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/.electron-gyp/13.1.8/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/austin/.electron-gyp/13.1.8',
gyp info spawn args   '-Dnode_gyp_dir=/home/austin/nody-greeter/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/austin/.electron-gyp/13.1.8/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/austin/nody-greeter/node_modules/node-gtk',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠴ Building module: node-gtk, Completed: 0/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --cflags gobject-introspection-1.0 cairo' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/austin/nody-greeter/node_modules/node-gtk'.
Error: `gyp` failed with exit code: 1



Error: node-gyp failed to rebuild '/home/austin/nody-greeter/node_modules/node-gtk'.
Error: `gyp` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/cli.js:146:9
Building with prefix: /usr
Bindings copied
⠙ Compiling bindings with electron-rebuild...Error: Command failed: npx electron-rebuild -m .
- Searching dependency tree
gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
(node:3361) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/js/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/.electron-gyp/13.1.8/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/austin/.electron-gyp/13.1.8',
gyp info spawn args   '-Dnode_gyp_dir=/home/austin/nody-greeter/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/austin/.electron-gyp/13.1.8/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/austin/nody-greeter/js/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: g++: No such file or directory
make: *** [screensaver.target.mk:111: Release/obj.target/screensaver/screensaver.o] Error 127
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/cli.js:146:9

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'npx electron-rebuild -m .'
}
✖ electron-rebuild failed
Password: 
nody-greeter is not built
Building with prefix: /usr
Bindings copied
⠙ Compiling bindings with electron-rebuild...Error: Command failed: npx electron-rebuild -m .
- Searching dependency tree
gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
gyp WARN EACCES current user ("austin") does not have permission to access the dev dir "/root/.electron-gyp/13.1.8"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
(node:3418) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/js/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/.node-gyp/13.1.8/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/tmp/.node-gyp/13.1.8',
gyp info spawn args   '-Dnode_gyp_dir=/home/austin/nody-greeter/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/tmp/.node-gyp/13.1.8/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/austin/nody-greeter/js/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: g++: No such file or directory
make: *** [screensaver.target.mk:111: Release/obj.target/screensaver/screensaver.o] Error 127
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/cli.js:146:9

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'npx electron-rebuild -m .'
}
✖ electron-rebuild failed

Inspiron_15_3567% npm audit fix                                     


removed 1 package, changed 17 packages, and audited 463 packages in 4s

40 packages are looking for funding
  run `npm fund` for details

# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix
Inspiron_15_3567%                                                     

npm install
npm run rebuild
npx tsc --build
node make build
sudo node make install

up to date, audited 463 packages in 1s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> nody-greeter@1.2.1 rebuild
> electron-rebuild -w node-gtk

⠸ Building module: node-gtk, Completed: 0gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
⠼ Building module: node-gtk, Completed: 0(node:4949) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gtk/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/.electron-gyp/13.6.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/austin/.electron-gyp/13.6.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/austin/nody-greeter/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/austin/.electron-gyp/13.6.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/austin/nody-greeter/node_modules/node-gtk',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠴ Building module: node-gtk, Completed: 0/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --cflags gobject-introspection-1.0 cairo' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/austin/nody-greeter/node_modules/node-gtk'.
Error: `gyp` failed with exit code: 1



Error: node-gyp failed to rebuild '/home/austin/nody-greeter/node_modules/node-gtk'.
Error: `gyp` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/cli.js:146:9
Building with prefix: /usr
Bindings copied
⠙ Compiling bindings with electron-rebuild...Error: Command failed: npx electron-rebuild -m .
- Searching dependency tree
gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
(node:5023) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/js/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/.electron-gyp/13.6.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/austin/.electron-gyp/13.6.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/austin/nody-greeter/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/austin/.electron-gyp/13.6.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/austin/nody-greeter/js/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: g++: No such file or directory
make: *** [screensaver.target.mk:111: Release/obj.target/screensaver/screensaver.o] Error 127
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/cli.js:146:9

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'npx electron-rebuild -m .'
}
✖ electron-rebuild failed
nody-greeter is not built
Building with prefix: /usr
Bindings copied
⠙ Compiling bindings with electron-rebuild...Error: Command failed: npx electron-rebuild -m .
- Searching dependency tree
gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
gyp WARN EACCES current user ("austin") does not have permission to access the dev dir "/root/.electron-gyp/13.6.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
(node:5074) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/js/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/austin/nody-greeter/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/.node-gyp/13.6.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/tmp/.node-gyp/13.6.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/austin/nody-greeter/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/tmp/.node-gyp/13.6.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/austin/nody-greeter/js/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: g++: No such file or directory
make: *** [screensaver.target.mk:111: Release/obj.target/screensaver/screensaver.o] Error 127
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/home/austin/nody-greeter/js/bindings'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Rebuilder.rebuildModuleAt (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/austin/nody-greeter/node_modules/electron-rebuild/lib/src/cli.js:146:9

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'npx electron-rebuild -m .'
}
✖ electron-rebuild failed
Inspiron_15_3567% 


```

But last time when I tried to install in Void Linux, it worked?
Thank you

**Comment by JezerM** [comment]
Basically, here's the problem:

```
Call to 'pkg-config --cflags gobject-introspection-1.0 cairo' returned exit status 127 while in binding.gyp
```

`gobject-introspection` and `cairo` packages are not found by pkg-config. Therefore, it seems they are not installed.

**Comment by austinrojers** [comment]
```
Inspiron_15_3567% sudo xbps-install gobject-introspection cairo
Package `gobject-introspection' already installed.
Package `cairo' already installed.

```
But I had already installed for web-greeter.

**Comment by JezerM** [comment]
Maybe, as you did a fresh install, `pkg-config` is not available, and so other programs like `g++` and `make`. Installing the `base-devel` package should "fix" this issue.

**Comment by austinrojers** [comment]
Yeah, that was exactly the issue.
Now all my Void specific issues with _nody_ and _web-greeter_ have been solved!

Thanks a lot, you have been very patient and friendly 😃.

Now is it possible, these two greeters can be shipped as a flatpak, it would make installation easier on any distro.

Now I have some _aether_ theme bugs which is common for both Ubuntu and my Void installation, where shall I post them?
😉

**Comment by JezerM** [comment]
Nice~

And yeah, I was thinking about creating a xbps package if possible. But a flatpak could be great~

About Aether bugs, it's probably that they won't be answered/resolved in the main repo, as it's kind of abandoned... so, you could create issues on my fork :D

**Comment by JezerM** [comment]
Ah, sorry, now you can xd

**Comment by JezerM** [comment]
@austinrojers Sadly, due to the nature of Flatpaks about [filesystem access](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access), it would be impossible to ship **nody-greeter** as a flatpak. Basically, not having access to `/etc` and `/usr` would make it unusable; besides, I couldn't make it to access to the LightDM session, so less useful.

**Comment by austinrojers** [comment]
> @austinrojers Sadly, due to the nature of Flatpaks about [filesystem access](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access), it would be impossible to ship **nody-greeter** as a flatpak. Basically, not having access to `/etc` and `/usr` would make it unusable; besides, I couldn't make it to access to the LightDM session, so less useful.

Greetings @JezerM, hope you are doing well, thanks for the acknowledgment, I understand the problem here.
✌️
